<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConferenceHotelMapRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConferenceHotelMapRepository extends EntityRepository
{
    #TODO: DELETE THIS FILE
}
