#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# For showing what DEFAULT controller method is called when a specific path is accessed.

# the structure for making a new path is as follows:
#   _controller: <bundle>:<class_name>:<method_name>

# TODO: add a crap load of routes as needed

_welcome:
    path:      /
    defaults:  { _controller: AppBundle:Homepage:homepage }

# main conference page (right now used for conference creation)
conference:
    path:      /conference
    defaults:  { _controller: AppBundle:Conference:conference }

conference_show:
    path:      /conference/{conf_id}/
    defaults:  { _controller: AppBundle:Conference:show }

conference_reg:
    path:      /conference/{conf_id}/register
    defaults:  { _controller: AppBundle:ConferenceRegistration:conferenceRegistration }

conference_edit:
    path:      /conference/{conf_id}/edit
    defaults:  { _controller: AppBundle:Conference:edit }

conference_delete:
    path:      /conference/{conf_id}/delete
    defaults:  { _controller: AppBundle:Conference:delete }

# main hotel page (right now used for hotel creation)
hotel:
    path:      /hotel
    defaults:  { _controller: AppBundle:Hotel:hotel }

