#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# For showing what DEFAULT controller method is called when a specific path is accessed.

# the structure for making a new path is as follows:
#   _controller: <bundle>:<class_name>:<method_name>

# TODO: add a crap load of routes as needed

_welcome:
    path:      /
    defaults:  { _controller: AppBundle:Homepage:homepage }

conference:
    path:      /conference
    defaults:  { _controller: AppBundle:Conference:conference }

conference_edit:
    path:      /conference/{conf_id}/edit
    defaults:  { _controller: AppBundle:Conference:edit }

hotel:
    path:      /hotel
    defaults:  { _controller: AppBundle:Hotel:hotel }
