#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# For showing what DEFAULT controller method is called when a specific path is accessed.

# the structure for making a new path is as follows:
#   _controller: <bundle>:<class_name>:<method_name>

# for each category we want to have show_all, create, show, edit, delete

_welcome:
    path:      /
    defaults:  { _controller: AppBundle:Homepage:homepage }

admin:
    path:      /admin
    defaults:  { _controller: AppBundle:Admin:admin }

transportation:
    path:      /transportation
    defaults:  { _controller: AppBundle:Admin:transportation }

# CONFERENCES
conference_show_all:
    path:      /conference
    defaults:  { _controller: AppBundle:Homepage:homepage }

conference_create:
    path:      /conference/create
    defaults:  { _controller: AppBundle:Conference:create }

conference_show:
    path:      /conference/{conf_id}
    defaults:  { _controller: AppBundle:Conference:show }

conference_edit:
    path:      /conference/{conf_id}/edit
    defaults:  { _controller: AppBundle:Conference:edit }

conference_delete:
    path:      /conference/{conf_id}/delete
    defaults:  { _controller: AppBundle:Conference:delete }

# CONFERENCE REGISTRATIONS
conf_reg_show_all:
    path:      /conference_registration
    defaults:  { _controller: AppBundle:ConferenceRegistration:showAll }

conf_reg_create:
    path:      /conference/{conf_id}/register
    defaults:  { _controller: AppBundle:ConferenceRegistration:create }

conf_reg_show:
    path:      /conference_registration/{conf_reg_id}
    defaults:  { _controller: AppBundle:ConferenceRegistration:show }

conf_reg_edit:
    path:      /conference_registration/{conf_reg_id}/edit
    defaults:  { _controller: AppBundle:ConferenceRegistration:edit }

conf_reg_delete:
    path:      /conference_registration/{conf_reg_id}/delete
    defaults:  { _controller: AppBundle:ConferenceRegistration:delete }

# USERS
user_delete:
    path:      /profile/delete
    defaults:  { _controller: AppBundle:Profile:delete }

user_edit:
    path:      /profile/edit
    defaults:  { _controller: AppBundle:Profile:edit }

# HOTELS
hotel_show_all:
    path:      /hotel
    defaults:  { _controller: AppBundle:Hotel:showAll }

hotel_create:
    path:      /hotel/create
    defaults:  { _controller: AppBundle:Hotel:create }

hotel_show:
    path:      /hotel/{hotel_id}
    defaults:  { _controller: AppBundle:Hotel:show }

hotel_edit:
    path:      /hotel/{hotel_id}/edit
    defaults:  { _controller: AppBundle:Hotel:edit }

hotel_delete:
    path:      /hotel/{hotel_id}/delete
    defaults:  { _controller: AppBundle:Hotel:delete }

# HOTEL REGISTRATIONS
#hotel_reg_show_all:
#    path:      /hotel_registration
#    defaults:  { _controller: AppBundle:HotelRegistration:showAll }

hotel_reg_create:
    path:      /conference_registration/{conf_reg_id}/hotel_registration/create
    defaults:  { _controller: AppBundle:HotelRegistration:create }

hotel_reg_show:
    path:      /conference_registration/{conf_reg_id}/hotel_registration
    defaults:  { _controller: AppBundle:HotelRegistration:show }

hotel_reg_edit:
    path:      /conference_registration/{conf_reg_id}/hotel_registration/edit
    defaults:  { _controller: AppBundle:HotelRegistration:edit }

hotel_reg_delete:
    path:      /conference_registration/{conf_reg_id}/hotel_registration/delete
    defaults:  { _controller: AppBundle:HotelRegistration:delete }

# EVENTS
event_show_all:
    path:      /conference/{conf_id}/event
    defaults:  { _controller: AppBundle:Conference:show }

event_create:
    path:      /conference/{conf_id}/event/create
    defaults:  { _controller: AppBundle:Event:create }

event_show:
    path:      /conference/{conf_id}/event/{event_id}
    defaults:  { _controller: AppBundle:Event:show }

event_edit:
    path:      /conference/{conf_id}/event/{event_id}/edit
    defaults:  { _controller: AppBundle:Event:edit }

event_delete:
    path:      /conference/{conf_id}/event/{event_id}/delete
    defaults:  { _controller: AppBundle:Event:delete }

# EVENT REGISTRATIONS
event_reg_show_all:
    path:      /event_registration
    defaults:  { _controller: AppBundle:ConferenceRegistration:showAll }

event_reg_create:
    path:      /conference/{conf_id}/event/{event_id}/register
    defaults:  { _controller: AppBundle:EventRegistration:create }

event_reg_show:
    path:      /event_registration/{event_reg_id}
    defaults:  { _controller: AppBundle:ConferenceRegistration:showAll }

#event_reg_edit:
#    path:      /profile/event_registration/{event_reg_id}/edit
#    defaults:  { _controller: AppBundle:EventRegistration:edit }

event_reg_delete:
    path:      /event_registration/{event_reg_id}/delete
    defaults:  { _controller: AppBundle:EventRegistration:delete }
