#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# For showing what DEFAULT controller method is called when a specific path is accessed.

# the structure for making a new path is as follows:
#   _controller: <bundle>:<class_name>:<method_name>

# for each category we want to have main page, create, show, edit, delete

_welcome:
    path:      /
    defaults:  { _controller: AppBundle:Homepage:homepage }

# CONFERENCES
conference:
    path:      /conference
    defaults:  { _controller: AppBundle:Homepage:homepage }

conference_create:
    path:      /conference/create
    defaults:  { _controller: AppBundle:Conference:create }

conference_show:
    path:      /conference/{conf_id}
    defaults:  { _controller: AppBundle:Conference:show }

conference_edit:
    path:      /conference/{conf_id}/edit
    defaults:  { _controller: AppBundle:Conference:edit }

conference_delete:
    path:      /conference/{conf_id}/delete
    defaults:  { _controller: AppBundle:Conference:delete }

# CONFERENCE REGISTRATIONS
conf_reg:
    path:      /profile/conference_registration
    defaults:  { _controller: AppBundle:Profile:show }

conf_reg_create:
    path:      /conference/{conf_id}/register
    defaults:  { _controller: AppBundle:ConferenceRegistration:create }

conf_reg_show:
    path:      /profile/conference_registration/{conf_reg_id}
    defaults:  { _controller: AppBundle:Profile:show }

conf_reg_edit:
    path:      /profile/conference_registration/{conf_reg_id}/edit
    defaults:  { _controller: AppBundle:ConferenceRegistration:edit }

conf_reg_delete:
    path:      /profile/conference_registration/{conf_reg_id}/delete
    defaults:  { _controller: AppBundle:ConferenceRegistration:delete }

# USERS
user_delete:
    path:      /profile/delete
    defaults:  { _controller: AppBundle:Profile:delete }

user_edit:
    path:      /profile/edit
    defaults:  { _controller: AppBundle:Profile:edit }

# HOTELS
hotel:
    path:      /hotel
    defaults:  { _controller: AppBundle:Homepage:homepage }

hotel_create:
    path:      /hotel/create
    defaults:  { _controller: AppBundle:Hotel:create }

hotel_show:
    path:      /hotel/{hotel_id}
    defaults:  { _controller: AppBundle:Hotel:show }

hotel_edit:
    path:      /hotel/{hotel_id}/edit
    defaults:  { _controller: AppBundle:Hotel:edit }

hotel_delete:
    path:      /hotel/{hotel_id}/delete
    defaults:  { _controller: AppBundle:Hotel:delete }

# EVENTS
# I think this should be /conference/{conf_id}/event/create
event:
    path:      /event/{conf_id}/
    defaults:  { _controller: AppBundle:Event:event } 

event_show:
    path:      /conference/{conf_id}/event/{event_id}
    defaults:  { _controller: AppBundle:Event:show }

event_edit:
    path:      /conference/{conf_id}/event/{event_id}/edit
    defaults:  { _controller: AppBundle:Event:edit }

event_delete:
    path:      /conference/{conf_id}/event/{event_id}
    defaults:  { _controller: AppBundle:Event:delete }

# EVENT REGISTRATIONS
# I think this should be /conference/{conf_id}/event/register
event_reg:
    path:      /event/{conf_id}/{event_id}/register
    defaults:  { _controller: AppBundle:EventRegistration:eventRegistration }

event_reg:
    path:      /profile/event_registration/{event_reg_id}/edit
    defaults:  { _controller: AppBundle:EventRegistration:edit }
