# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_USER:        ROLE_USER
        ROLE_ADMIN:      [ROLE_USER, ROLE_CONFERENCE_MANAGER, ROLE_BOOKINGS_MANAGER]
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_CONFERENCE_MANAGER: ROLE_CONFERENCE_MANAGER
        ROLE_BOOKINGS_MANAGER: ROLE_BOOKINGS_MANAGER
        #TODO: find a way to provide user-friendly names for roles.
        #might find this in a library or some role class.

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                #login_path: fos_user_security_login
                #check_path: fos_user_security_check
                #always_use_default_target_path: false
                #default_target_path: /
                #use_referer: true
            logout:    
                path: fos_user_security_logout 
                target: _welcome
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        #∫- { path: ^/conference$, role: ROLE_CONFERENCE_MANAGER } #create new conference
        - { path: ^/conference/.*/edit, role: ROLE_CONFERENCE_MANAGER } # edit conference

        #TODO: try replacing this by annotations in each controller
        #- must figure out how to make custom message work
        #TODO: make custom page for unauthorized page - better user experience
